apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiered-storage-oss
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: alicloud-sc-oss